name: docker build and deployment
on:
  workflow_dispatch:
    inputs:
      tag:
        description: version  tag for docker image
        required: true
        default: 'latest'
jobs:
  build-python-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Run Docker build command
        run: docker build -t subin1devops/pyapp:latest .
      - name: Login to Docker
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT_KEY }}
      - name: push to dockerhub
        run: docker push subin1devops/pyapp:latest

  Deploy-to-aws:
    needs: build-python-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: copy content
        run: echo "${{ secrets.SSH_KEY}}" > devops-tos.pem
      - name: Give permission to aws
        run: chmod 600 devops-tos.pem
      - name: login to server
        run: |
          ssh -o StrictHostKeyChecking=no -i devops-tos.pem  ${{ vars.SSH_USER }}@${{ vars.SERVER_IP }} << 'ENDSSH'
          docker pull subin1devops/pyapp:latest
          docker run -d -p 7072:8000 subin1devops/pyapp:latest
          ENDSSH





