name: docker build and deployment
on:
  workflow_dispatch:
    inputs:
      tag:
        description: version  tag for docker image
        required: true
        default: 'latest'
jobs:
  build-python-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Run Docker build command
        run: docker build -t subin1devops/pyapp:latest
      - name: Login to Docker
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT_KEY }}
      - name: push to dockerhub
        run: docker push subin1devops/pyapp:latest
          
      


